# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/WashU/CSE/CSE 462/XADC/XADC v4/HW1.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WashU/CSE/CSE 462/XADC/XADC v4/HW1.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/WashU/CSE/CSE 462/XADC/XADC v4/HW1.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/WashU/CSE/CSE 462/XADC/XADC v4/HW1.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci
# IP: The module: 'xadc_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WashU/CSE/CSE 462/XADC/XADC v4/HW1.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/WashU/CSE/CSE 462/XADC/XADC v4/HW1.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xadc_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
